spring.application.name=research-publication-management

spring.data.mongodb.uri=mongodb://localhost:27017/researchdb

spring.data.mongodb.database=researchdb

server.port=8080

springdoc.swagger-ui.path=/swagger-ui.html